### ISSUE TITLE
Serious issue

### ISSUE THREAD

**Issue by partywarp** [renaissancedog/renaissancedog#1]
TLDR; I need to find a big number
[Scroll down and pick the C# tab](https://jb.gg/mono)
https://jb.gg/correctNumberIs${correct number here}⬅️Check your answer here
```csharp
class GolombSequence
{
   static long G(long n)
   {
       return n == 1 ? 1 : 1 + G(n - G(G(n - 1)));
   }
   static void Main(string[] args)
   {
       var sum = Enumerable.Range(1, 100000000).Sum(i => G(i)); // C# ranges are inclusive
       Console.WriteLine("https://jb.gg/correctNumberIs" + sum);
   }
}
```
⬆️Jetbrains provides us with this starter code (ofc you can't use this because it will never finish in time)
```cpp
#include <bits/stdc++.h>
using namespace std;
long long previous_values[100000001];
long long g(long long n){
   if(previous_values[n]==0)
       return (previous_values[n]=(n==1?1:1+g(n-g(g(n-1)))));
   else
       return previous_values[n];
}
int main(){
   int sum=0;
   for(int i=1;i<=100000000;i++){
       sum+=g(i);
   }
   cout<<"https://jb.gg/correctNumberIs"<<sum<<endl;
}
```
⬆️Said C++ code utilizing Dynamic programming
I need to find the correct number (do not ask why)

**Comment by greatnesshere** [comment]
Working document here: https://docs.google.com/document/d/1_rgi9WqqrCHKQJ50GFmBo7_3RcvQ87sSpF6AXkaLvmA/edit?usp=sharing

**Comment by renaissancedog** [comment]
Irrelevant to this repo

**Comment by partywarp** [comment]
I object

@renaissancedog is simply making ridiculous claims to hide his competitive programming incompetence!
