### ISSUE TITLE
This means war

### ISSUE THREAD

**Issue by greatnesshere** [renaissancedog/renaissancedog#1]
I officially declare war on your stupid README

You may not delete my issues. Those were good first issues for newcomers.

**Comment by renaissancedog** [comment]
@greatnesshere is wasting my time. I will now formally accuse him of being a fan of vanilla JS.

**Comment by renaissancedog** [comment]
doesn't work on my machine

**Comment by greatnesshere** [comment]
Henceforth, let it be known throughout the realm that I, with full accord, do affirm @renaissancedog’s proclamation that my heart delights in the pure essence of vanilla JS. Verily, vanilla JS stands as the finest choice, untainted by the shadow of Facebook/Meta’s influence.

**Comment by renaissancedog** [comment]
@greatnesshere admitted it-he loves vanilla JS.

By decree, he is banned from the realm

**Comment by greatnesshere** [comment]
I love you 🥰
