### ISSUE TITLE
Numpy is not a framework

### ISSUE THREAD

**Issue by partywarp** [renaissancedog/renaissancedog#2]
My first legitimate issue

**Comment by partywarp** [comment]
Neither is Pandas

Please kindly take these down. I will be filing a cease and desist shortly

**Comment by renaissancedog** [comment]
added 'libraries'
fixed

**Comment by partywarp** [comment]
Buddy I could put every Python standard library

**Comment by renaissancedog** [comment]
Those don't count

**Comment by partywarp** [comment]
@renaissancedog why not

**Comment by renaissancedog** [comment]
Bc I said so

**Comment by partywarp** [comment]
sigma
