### ISSUE TITLE
You don't use Arch Linux

### ISSUE THREAD

**Issue by greatnesshere** [renaissancedog/renaissancedog#3]
Arch Linux is too hard for you

**Comment by greatnesshere** [comment]
Send proof no balls

**Comment by renaissancedog** [comment]
These allegations are misleading and outright lies. OP has no evidence against me.

Closed

**Comment by greatnesshere** [comment]
Deriving from the closure of this issue as not planned, I can deduce that @renaissancedog does not plan to use Arch Linux in the future.

**Comment by renaissancedog** [comment]
@greatnesshere 's ridiculous comments are nothing short of slanderous. I vehemently deny any such claim as outright baseless lies.

**Comment by greatnesshere** [comment]
bot
