### ISSUE TITLE
Java sucks

### ISSUE THREAD

**Issue by greatnesshere** [renaissancedog/renaissancedog#4]
Don't use Java.

Java has no documentation.

JavaScript inherits it's horrible qualities from it's daddy Java.

Java forces you to use long function names for things that should be automatic.

Java enforces the worst possible underlying implementation for all of it's algorithms.

Java's standard library is not at all competent.

Java does not support operator overloading.

(To be continued)

**Comment by renaissancedog** [comment]
better than C++

- segfaults
- Illegal memory access
- terrible learning curve

**Comment by renaissancedog** [comment]
C++ _is_ faster though

**Comment by greatnesshere** [comment]
> better than C++
> 
> * segfaults
> * Illegal memory access
> * terrible learning curve

Cap

**Comment by renaissancedog** [comment]
Crowdstrike got them
And it shut down the global economy for a day 

_laughs in nullPointerException_

**Comment by greatnesshere** [comment]
it was not `java.lang.NullPointerException` it was a kernel file overwrite

**Comment by renaissancedog** [comment]
i know
further evidence c++ is unsafe

**Comment by greatnesshere** [comment]
I have no idea what you are talking about

**Comment by greatnesshere** [comment]
> i know further evidence c++ is unsafe

More like evidence Windows is unsafe and Mac is better
